Repository ZootopiaContact/ZootopiaContact, pull requests merged in 2023-09, with the labels that each got.

#1 Feature/contactInfo
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/kotlinc.xml
  .idea/misc.xml
  .idea/vcs.xml
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/example/zootopiapage/ExampleInstrumentedTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/zootopiapage/Adapter.kt
  app/src/main/java/com/example/zootopiapage/Constants.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/ZootopiaInfo.kt
  app/src/main/java/com/example/zootopiapage/contact.kt
  app/src/main/java/com/example/zootopiapage/mypage.kt
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/apple.png
  app/src/main/res/drawable/cider.png
  app/src/main/res/drawable/flurry.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/jackson.png
  app/src/main/res/drawable/jjuni.png
  app/src/main/res/drawable/judy.png
  app/src/main/res/drawable/michel.png
  app/src/main/res/drawable/nook.png
  app/src/main/res/drawable/pach.png
  app/src/main/res/drawable/yobi.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_contact.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/main/res/xml/backup_rules.xml
  app/src/main/res/xml/data_extraction_rules.xml
  app/src/test/java/com/example/zootopiapage/ExampleUnitTest.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: Feature⚙️

#2 [FEAT] : 디자인 UI 추가
  app/build.gradle
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/contact.kt
  app/src/main/res/drawable/backgroundbottom.xml
  app/src/main/res/drawable/backgroundtop.xml
  app/src/main/res/drawable/mailicon.png
  app/src/main/res/drawable/phoneicon.png
  app/src/main/res/layout/fragment_mypage.xml
Labels: Design🎨

#3 [FEAT]: Contact UI
  app/src/main/java/com/example/zootopiapage/Adapter.kt
  app/src/main/java/com/example/zootopiapage/contact.kt
  app/src/main/res/drawable/empty_heart.png
  app/src/main/res/drawable/heart.png
  app/src/main/res/drawable/piter.png
  app/src/main/res/drawable/profile_background.xml
  app/src/main/res/layout/contact_list.xml
  app/src/main/res/layout/fragment_contact.xml
Labels: Conflict💥, Design🎨

#4 [FIX] : 좋아하는 말 삭제
  app/build.gradle
  app/src/main/res/layout/fragment_mypage.xml
Labels: Design🎨

#5 [FEAT]: 연락처 기능 및 UI
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/ViewPagerAdapter.kt
  app/src/main/java/com/example/zootopiapage/ZootopiaData.kt
  app/src/main/java/com/example/zootopiapage/ZootopiaInfo.kt
  app/src/main/java/com/example/zootopiapage/contact.kt
  app/src/main/res/drawable/empty_heart.png
  app/src/main/res/drawable/heart.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_list.xml
  app/src/main/res/layout/fragment_contact.xml
Labels: Design🎨, Feature⚙️

#6 [FEAT]: 연락처 기능 및 UI
  app/src/main/java/com/example/zootopiapage/ContactAdapter.kt
  app/src/main/res/drawable/empty_heart.xml
  app/src/main/res/drawable/heart.xml
  app/src/main/res/drawable/heart_selector.xml
  app/src/main/res/layout/contact_list.xml
  app/src/main/res/layout/fragment_contact_list.xml
Labels: Design🎨, Feature⚙️

#7 [FIX] : 뷰페이저1에서 2로 수정!
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/MypageFragment.kt
  app/src/main/java/com/example/zootopiapage/ViewPager2Adapter.kt
  app/src/main/java/com/example/zootopiapage/ViewPagerAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feature⚙️, Fix🔧

#8 Feature/floating button
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/MypageFragment.kt
  app/src/main/java/com/example/zootopiapage/ViewPager2Adapter.kt
  app/src/main/res/drawable/floating_img.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: Feature⚙️

#9 [FEAT]: 연락처 Grid UI 추가
  app/src/main/java/com/example/zootopiapage/ContactAdapter.kt
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/grid_contact_list.xml
Labels: Design🎨, Feature⚙️

#11 Feature/dialog
  app/build.gradle
  app/src/main/java/com/example/zootopiapage/ContactAdapter.kt
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/java/com/example/zootopiapage/DialogAddItemFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/ZootopiaData.kt
  app/src/main/res/drawable/apple.png
  app/src/main/res/drawable/birth_background.png
  app/src/main/res/drawable/call_background.png
  app/src/main/res/drawable/cider.png
  app/src/main/res/drawable/email_background.png
  app/src/main/res/drawable/floating_img.png
  app/src/main/res/drawable/flurry.png
  app/src/main/res/drawable/jackson.png
  app/src/main/res/drawable/jjuni.png
  app/src/main/res/drawable/judy.png
  app/src/main/res/drawable/marti.png
  app/src/main/res/drawable/michel.png
  app/src/main/res/drawable/name_background.png
  app/src/main/res/drawable/name_shape.xml
  app/src/main/res/drawable/nook.png
  app/src/main/res/drawable/pach.png
  app/src/main/res/drawable/piter.png
  app/src/main/res/drawable/yobi.png
  app/src/main/res/font/font.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_list.xml
  app/src/main/res/layout/dialog_add_item.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_dialog_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/grid_contact_list.xml
  app/src/main/res/values/colors.xml
Labels: Feature⚙️

#15 [FEAT] : 스플래쉬 화면 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/StartActivity.kt
  app/src/main/res/drawable/splash.png
  app/src/main/res/layout/activity_start.xml
  app/src/main/res/values/themes.xml
Labels: Design🎨, Feature⚙️

#16 Feat/add list item
  app/src/main/java/com/example/zootopiapage/ContactAdapter.kt
  app/src/main/java/com/example/zootopiapage/ContactDetailFragment.kt
  app/src/main/java/com/example/zootopiapage/ContactListFragment.kt
  app/src/main/java/com/example/zootopiapage/DialogAddItemFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/MypageFragment.kt
  app/src/main/java/com/example/zootopiapage/OnItemAddedListener.kt
  app/src/main/java/com/example/zootopiapage/ViewPager2Adapter.kt
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_dialog_add_item.xml
  app/src/main/res/values/dimens.xml
Labels: Feature⚙️

#17 [FIX] : 백그라운드 배경 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
Labels: Fix🔧

#18 UI/last fix
  app/src/main/res/drawable/empty_heart.xml
  app/src/main/res/drawable/heart.xml
  app/src/main/res/drawable/leaf.png
  app/src/main/res/drawable/logo_icon.png
  app/src/main/res/drawable/message.xml
  app/src/main/res/drawable/panta.png
  app/src/main/res/drawable/profile_background.xml
  app/src/main/res/drawable/tab_layout_border.xml
  app/src/main/res/drawable/telephone.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/contact_list.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_dialog_add_item.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/grid_contact_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/style.xml
Labels: Design🎨

#19 [FEAT] App Icon 추가 및 App Bar 높이 수정
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_contact_list.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: Design🎨

#20 [Fix] 최종 수정 1차
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/zootopiapage/ContactAdapter.kt
  app/src/main/java/com/example/zootopiapage/ContactDetailFragment.kt
  app/src/main/java/com/example/zootopiapage/MainActivity.kt
  app/src/main/java/com/example/zootopiapage/ViewPager2Adapter.kt
  app/src/main/res/layout/activity_main.xml
Labels: Fix🔧

#21 [Design] app icon 사진 변경
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/mipmap-anydpi-v26/zootopia_icon.xml
  app/src/main/res/mipmap-anydpi-v26/zootopia_icon_round.xml
  app/src/main/res/mipmap-hdpi/app_icon.png
  app/src/main/res/mipmap-hdpi/zootopia_icon.png
  app/src/main/res/mipmap-hdpi/zootopia_icon_round.png
  app/src/main/res/mipmap-mdpi/app_icon.png
  app/src/main/res/mipmap-mdpi/zootopia_icon.png
  app/src/main/res/mipmap-mdpi/zootopia_icon_round.png
  app/src/main/res/mipmap-xhdpi/app_icon.png
  app/src/main/res/mipmap-xhdpi/zootopia_icon.png
  app/src/main/res/mipmap-xhdpi/zootopia_icon_round.png
  app/src/main/res/mipmap-xxhdpi/app_icon.png
  app/src/main/res/mipmap-xxhdpi/zootopia_icon.png
  app/src/main/res/mipmap-xxhdpi/zootopia_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/app_icon.png
  app/src/main/res/mipmap-xxxhdpi/zootopia_icon.png
  app/src/main/res/mipmap-xxxhdpi/zootopia_icon_round.png
  app/src/main/res/values/zootopia_icon_background.xml
  app/src/main/zootopia_icon-playstore.png
Labels: Design🎨
